# Imports format
group_imports       = "StdExternalCrate"
imports_granularity = "Crate"

# Code format
comment_width            = 110
format_strings           = true
max_width                = 100
newline_style            = "Unix"
overflow_delimited_expr  = true
reorder_impl_items       = true
struct_lit_single_line   = false
use_field_init_shorthand = true

format_code_in_doc_comments = true
# imports_layout              = "Vertical"
wrap_comments = true
